### ISSUE TITLE
Les Tags sont statiques

### ISSUE THREAD

**Issue by Nabisso** [isma237/StopEc2InstanceByTag#2]
Hello,

Les tags recherchés sont écris en dur dans le code. il faut les demander en paramètres afin de rendre le programme dynamique

Merci

**Comment by isma237** [comment]
Bien reçu.
J'intègre cet update.

**Comment by isma237** [comment]
Terminé

**Comment by Nabisso** [comment]
Great job. 
You can merge branches. 

Take a minute to write a AWsome documentation
